
@startuml
hide circle
skinparam defaultFontName Monospaced
skinparam monochrome true
skinparam classAttributeIconSize 0

class Calculator{
	+byte add(byte a, byte b)
	+byte sub(byte a, byte b)
}
class HalfAdder{
    	+getSum(boolean a, boolean b)
    	+getCarry(boolean a, boolean b)	
}

class FullAdder{
    	+getSum(boolean a, boolean b, boolean carryIn)
    	+getCarry(boolean a, boolean b, boolean carryIn)	
}


Calculator *-- "8" FullAdder
FullAdder *-- "2" HalfAdder

@enduml